version: '3.7'
services:
  test:
    build:
      context: ../..
      dockerfile: ./packages/model-runner/Dockerfile
      target: test

  release:
    build:
      context: ../..
      dockerfile: ./packages/model-runner/Dockerfile
      target: release
    # This is set this way to make things easier in the Actions workflows.
    image: image

  run-model:
    build:
      context: ../..
      dockerfile: ./packages/model-runner/Dockerfile
      target: release
    environment:
      - GITHUB_RUN_ID=local
      - MODEL_RUNNER_OUTPUT_DIR=/data/output
      - AZURE_STORAGE_ACCOUNT
      - AZURE_STORAGE_CONTAINER
      - DOCKER_USER
      - DOCKER_PASSWORD
      - WOLFRAM_USER
      - WOLFRAM_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test/test-job-mrc-ide-covidsim.json:/data/input/inputFile.json:rw
      - ./output:/data/output:rw
      - ./log:/data/log:rw
    command: /data/input/inputFile.json

  remote-image:
    image: docker.pkg.github.com/${GITHUB_REPO:-covid-modeling/model-runner}/model-runner:master
    environment:
      - GITHUB_RUN_ID=local
      - MODEL_RUNNER_OUTPUT_DIR=/data/output
      - AZURE_STORAGE_ACCOUNT
      - AZURE_STORAGE_CONTAINER
      - DOCKER_USER
      - DOCKER_PASSWORD
      - WOLFRAM_USER
      - WOLFRAM_PASSWORD
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test/test-job-mrc-ide-covidsim.json:/data/input/inputFile.json:ro
      - ./output:/data/output:rw
      - ./log:/data/log:rw
    command: /data/input/inputFile.json
